### ISSUE TITLE
Branch name change

### ISSUE THREAD

**Issue by RyanDavies19** [FloatingArrayDesign/MoorDyn#112]
@sanguinariojoe would it be relatively easy to change the v2 to the master branch and to retire v1 to a separate branch? @mattEhall and I were discussing and thought that it would be good to do this switch since our goal is for v2 to be the branch that is used.

**Comment by sanguinariojoe** [comment]
Nope, piece of cake actually. I'll send you a how to tomorrow

**Comment by RyanDavies19** [comment]
Great thanks!

**Comment by sanguinariojoe** [comment]
First, I cannot know the members of the FloatingArrayDesign organization, neither their roles. I can do this, but I rather let someone from the NREL to take care. In general I will keep my hands out of master. No idea if you @RyanDavies19 have rights to do this.

OK, let's start!

1. **Clean copy**

To avoid confusions and mistakes, first thing we are doing is getting a clean copy of this repo (not our forks), on a MoorDyn.upstream folder:

```
git clone git@github.com:FloatingArrayDesign/MoorDyn.git MoorDyn.upstream
cd MoorDyn.upstream
git fetch origin
```

2. **Save master as a tag**

A tag is just a read-only branch. I really thing we do not want to have a v1 branch, as long as we are not developing it anymore. We can anyway start such a branch from the tag on the future.

```
git tag v1.01.03
git push origin v1.01.03
```

3. **Replace master by v2**

Let's do what we came to do!

```
git reset --hard origin/v2
git push -f origin master
```

I suppose we also want to sync dev branch,

```
git checkout dev
git reset --hard origin/v2
git push -f origin dev
git checkout master
```
 
4. **Tidy up a bit**

Now we do not need v2 branch anymore, as well as some other branches which seem pretty useless:

```
git push -d dev2
git push -d matt_current
git push -d v2
git push -d v2-make-wheels
```

**Comment by RyanDavies19** [comment]
@sanguinariojoe Thanks for the tips. I'll chat with Matt about permissions.

**Comment by RyanDavies19** [comment]
Branches have been updated. V2 has been changed to master, and the master branch has been changed to v1
