### ISSUE TITLE
NaN value detected in MoorDyn state at dynamic relaxation

### ISSUE THREAD

**Issue by Fandier** [FloatingArrayDesign/MoorDyn#124]
Hello, everyone.
I am getting an error while using matlab to call MoorDyn.ll which I downloaded in advance from the internet. I just changed the lines.txt from spar to oc4, but it seems to have a problem with the initialisation. Can anyone help me with this problem?
![image](https://github.com/FloatingArrayDesign/MoorDyn/assets/73537352/c73dc927-8a40-419a-a133-a346082950e7)

![image](https://github.com/FloatingArrayDesign/MoorDyn/assets/73537352/d697c283-2e88-45d4-8794-6e1a6d2bfef9)

**Comment by sanguinariojoe** [comment]
Stop using MoorDyn v1 please. You have the documentation on how to use MoorDyn v2 [here](https://moordyn.readthedocs.io/en/latest/). In such documentation you also have the answer to your question regarding diverging configurations (i.e. NaNs)

I hereby close this issue. If you have further issues with v2 please open new issues
