### ISSUE TITLE
dev docs rendering

### ISSUE THREAD

**Issue by RyanDavies19** [FloatingArrayDesign/MoorDyn#134]
Opening an issue so we can discuss rendering the dev docs on MoorDyn.readthedocs.io/en/latest. So far we have tried the following:

1. Specified sphinx_rtd_theme version per conversation in #129. This resolved the issue with bullet points not rendering however the max depth on the sidebar is now fixed at 2 and the menu to change builds in the bottom left corner is now broken. 

2. Changed toctree macdepth in index.rst to 5. This made no change. 

These issues don't seem to appear on MoorDyn-v2.readthedocs.io/en/latest, which is referencing the same docs folder in the dev branch. As far as we can tell this means there is an issue in how readthedocs is configured for MoorDyn.readthedocs.io/en/latest

**Comment by sanguinariojoe** [comment]
My general settings are quite normal:

![image](https://github.com/FloatingArrayDesign/MoorDyn/assets/1668392/32544d19-7fc7-4f70-b805-c33d4f673082)

The advanced ones seem also rather normal:

![image](https://github.com/FloatingArrayDesign/MoorDyn/assets/1668392/36f38977-b974-41a4-b5e0-e72c0898b710)
![image](https://github.com/FloatingArrayDesign/MoorDyn/assets/1668392/b1617d5c-e31c-4f6c-a551-295a4ccf634b)

**Comment by RyanDavies19** [comment]
That PR did not fix things. Looking at the [difference in build logs](https://www.diffchecker.com/Ufuj8Fx4/) at line 170, moordyun.readthedocs is installing pillow instead of sphinx and then pillow is installing a depreciated version of sphinx. It's strange because the settings are identical to what you have @sanguinariojoe  and what I have on moordyn-ryan.readthedocs

**Comment by RyanDavies19** [comment]
Created a dev_docs branch to test things on so that we don't fill up the dev branch with junk commits

**Comment by RyanDavies19** [comment]
Nothing I have tried has worked so I gave up and submitted an issue at readthedocs: readthedocs/readthedocs.org#10765

**Comment by RyanDavies19** [comment]
Resolved by deleting and remaking the project. @sanguinariojoe can we retire [moordyn-v2.readthedocs.io](https://moordyn-v2.readthedocs.io/en/latest/) now that [moordyn.readthedocs.io](https://moordyn.readthedocs.io/en/latest/) is built and properly formatted?

**Comment by sanguinariojoe** [comment]
https://moordyn-v2.readthedocs.io/en/latest/ is no more
