### ISSUE TITLE
WEC-Sim v6.0 MoorDyn v2 error

### ISSUE THREAD

**Issue by hachikoi1** [FloatingArrayDesign/MoorDyn#169]
Hi developers
I attempted to model a 1:70 scale model of UMaine VolturnUS-S semi-submersible platform in WEC-Sim V6.0 - MoorDyn V2-C. I checked the parameters in /Mooring/lines.txt, but the lines.log always reports an error: **ERR ../../source/Line.cpp:759 getStateDeriv(): NaN detected**.

I tried to modify almost every parameter, but the the error still persists. Could anyone help me to find out the error. 
[Here](https://github.com/FloatingArrayDesign/MoorDyn/files/13587537/WEC-Sim.zip) is my studied cases, the test model of UMaine VolturnUS-S semi-submersible platform. The information of 1:70 scale model can be found [here](https://www.ccp-wsi.ac.uk/data_repository/test_cases/test_case_015), and 1:1 model information is in [Definition of the UMaine VolturnUS-S Reference.pdf](https://github.com/WEC-Sim/WEC-Sim/files/13561451/Definition.of.the.UMaine.VolturnUS-S.Reference.pdf). 

Many thanks

Tuanyuan

**Comment by hachikoi1** [comment]
Hi AlexWKinley

    Many thanks for your reply. Is "time step" the simulation time step **dt** or the time step to use in mooring integration **dtM**? I tried to decrease the segment number to 20, as well as the simulation time step **dt** and time step to use in mooring integration  to 0.0001 or even smaller, but the error still exists. And sometimes a small time step can cause WEC-Sim to crash. 

Best regards,
Tianyuan

**Comment by RyanDavies19** [comment]
@hachikoi1 Jumping in to clarify the time steps here. dtM is the internal time step that Alex was referring to reducing. You can still leave the external time step, dt, at whatever works best for you. When dtM < dt, MoorDyn will subdivide dt into as many time steps as necessary to have an internal time step of dtM. When dt < dtM, MoorDyn will just use dt. The one caveat here is that MoorDyn will assume constant coupled state derivatives (velocities) over the time step dt.

**Comment by hachikoi1** [comment]
Hi @RyanDavies19, @AlexWKinley 
I tuned some parameters, including BA, dtM and NumSegs, but it doesn't work. And sometimes it can cause my simulation to crash. Now my simulation is rather unstable. Almost every time I run it, it makes my matlab unresponsive and quits. I'm not sure if this simulation instability is a version issue. I would post my WEC-Sim inpit file and lines.txt below
```
simu                            =  simulationClass();
simu.simMechanicsFile           =  'UMaine.slx';
simu.solver                     =  'ode4';
simu.explorer                   =  'off';
simu.startTime                  =  0;
simu.rampTime                   =  0;
simu.endTime                    =  100;
simu.dt                         =  0.01; % simu.dtOut = simu.dt
simu.gravity                    =  9.80665; % Default = 9.81
simu.rho                        =  998.2072; % Default = 1000
simu.outputDir                  =  'WECSimOutputs'; % Default = 'output'
simu.stateSpace                 =  0; % 0 (convolution integral), 1 (state-space). Default = 0
simu.cicDt                      =  simu.dt; % Default = 'dt'
simu.cicEndTime                 =  60; % Default = 60, recommended by OpenFAST
mooring(1)                      =  mooringClass('mooring');
mooring(1).moorDynLines         =  3;
mooring(1).moorDynNodes(1:3)    =  [21 21 21]; 
mooring(1).initial.displacement =  body(1).initial.displacement;
mooring(1).initial.axis         =  body(1).initial.axis;
mooring(1).initial.angle        =  body(1).initial.angle;

```


```
----------------------------------------------------------- MoorDyn INPUT FILE
1:70 scale model of the IEA 15MW reference wind turbine (IEA-15-240-RWT) and UMaine VolturnUS-S semi-submersible platform https://www.ccp-wsi.ac.uk/data_repository/test_cases/test_case_015
----------------------------------------------------------- LINE TYPES
TypeName       Diam           MassDen        EA             BA/-zeta       EI             Cd             Ca             CdAx           CaAx
(name)         (m)            (kg/m)         (N)            (N-s/-)        (N-m^2)        (-)            (-)            (-)            (-) 
Chain          0.0048         0.144          2.10E+06      -1.000          0.000          2.000          0.820          0.400          0.270
----------------------------------------------------------- POINTS                                           
ID             Attachment     X              Y              Z              M              V              CdA            CA
(#)            (word/ID)      (m)            (m)            (m)            (kg)           (m^3)          (m^2)          (-)
1              Fixed         -9.52500        0.00000       -2.86000        0.000          0.000          0.000          0.000
2              Fixed          4.41200       -7.65500       -2.86000        0.000          0.000          0.000          0.000
3              Fixed          4.41200        7.65500       -2.86000        0.000          0.000          0.000          0.000
4              Vessel        -0.83443        0.00000       -0.17798        0.000          0.000          0.000          0.000
5              Vessel         0.42437       -0.72680       -0.17798        0.000          0.000          0.000          0.000
6              Vessel         0.42437        0.72680       -0.17798        0.000          0.000          0.000          0.000
----------------------------------------------------------- LINES                                         
ID             LineType       AttachA        AttachB        UnstrLen       NumSegs        LineOutputs
(#)            (name)         (ID)           (ID)           (m)            (-)            (-)
1              Chain          1              4              9.685          20             tp
2              Chain          2              5              9.017          20             tp
3              Chain          3              6              9.017          20             tp
----------------------------------------------------------- SOLVER OPTIONS
0.00005                                                     dtM             - time step to use in mooring integration (s)
RK2                                                         tScheme         - time integrator
2.86                                                        WtrDpth         - water depth
9.80665                                                     g               - gravity acceleration (m/s^2)
998.2072                                                    rho             - water density (kg/m^3)
1.0                                                         dtIC      		- time interval for analyzing convergence during IC gen (s)
200.0                                                       TmaxIC    		- max time for ic gen (s)
0.001                                                       threshIC  		- threshold for IC convergence (-)   
5.0                                                         CdScaleIC 		- factor by which to scale drag coefficients during dynamic relaxation (-)
0                                                           WaveKin         - wave kinematics flag (0=neglect, the only option currently supported)
3.0E+06                                                     kbot            - bottom stiffness (Pa/m)
3.0E+05                                                     cbot      		- bottom damping (Pa-s/m)
2                                                           writeLog        - write a log file
1                                                           WriteUnits      - write the units header on the output files
----------------------------------------------------------- OUTPUTS                                  
FairTen1                                           
FairTen2                                            
FairTen3                                          
AnchTen1                                            
AnchTen2                                          
AnchTen3
-----------------------------------------------------------                          

```

**Comment by sanguinariojoe** [comment]
I did not traverse the config, nor tested it. Anyway, i would say matlab
becomes unresponsive because your time step is small (dtM = 5e-5) while
your convergence maximum time is large (TmaxIC = 200). Thus, MoorDyn would
spent 4e6 steps looking for a good initial condition.

You can first try to be less strict on the convergence criteria (currently
threshIC = 0.1%) and reduce the maximum time spent looking for such initial
condition.

Best,
Pepe

On Thu, 7 Dec 2023, 12:15 hachikoi, ***@***.***> wrote:

Hi @RyanDavies19 <https://github.com/RyanDavies19>, @AlexWKinley

**Comment by hachikoi1** [comment]
Hi @sanguinariojoe 
Matlab response loss doesn't occur during initialization, but in the first few time step of the simulation. lines.log looks all right, and lines.out outputs very few results. Then matlab loses its response and is forced to quit. I've tested the official WEC-Sim case and it pass. I suspect there is a problem with my settings somewhere. I've changed almost all the parameters and it still doesn't work.

lines.log
```
MoorDyn v2 log file with output level MSG at 'Mooring/lines.log'
Generated entities:
	nLineTypes  = 1
	nRodTypes   = 0
	nPoints     = 6
	nBodies     = 0
	nRods       = 0
	nLines      = 3
	nFails      = 0
	nFreeBodies = 0
	nFreeRods   = 0
	nFreePoints  = 0
	nCpldBodies = 0
	nCpldRods   = 0
	nCpldPoints = 3
Time integrator = 2nd order Runge-Kutta
No Waves or Currents, or set externally
Creating mooring system...
Initializing coupled Point 3 in -0.036164, -0.0031605, -0.146556...
Initializing coupled Point 4 in 0, 0, 0...
Initializing coupled Point 5 in 0, -1.06691e-308, -6.95252e-310...
  - Line1:
    ID: 1
    UnstrLen: 9.685
    N   : 20
    d   : 0.0048
    rho : 7957.75
    E   : 1.1605e+11
    EI  : 0
    BAin: -0.8
    Can : 0.82
    Cat : 0.27
    Cdn : 2
    Cdt : 0.4
    ww_l: 1.23544
Line 1 damping set to 1.17728e+07 Ns = 213.035 Pa-s, based on input of -0.8
WRN ../../source/Line.cpp:498 initialize(): Wrong catenary initial profile for Line, intializing as linear 1
Initialized Line 1
  - Line2:
    ID: 2
    UnstrLen: 9.017
    N   : 20
    d   : 0.0048
    rho : 7957.75
    E   : 1.1605e+11
    EI  : 0
    BAin: -0.8
    Can : 0.82
    Cat : 0.27
    Cdn : 2
    Cdt : 0.4
    ww_l: 1.23544
Line 2 damping set to 1.09608e+07 Ns = 198.341 Pa-s, based on input of -0.8
WRN ../../source/Line.cpp:498 initialize(): Wrong catenary initial profile for Line, intializing as linear 2
Initialized Line 2
  - Line3:
    ID: 3
    UnstrLen: 9.017
    N   : 20
    d   : 0.0048
    rho : 7957.75
    E   : 1.1605e+11
    EI  : 0
    BAin: -0.8
    Can : 0.82
    Cat : 0.27
    Cdn : 2
    Cdt : 0.4
    ww_l: 1.23544
Line 3 damping set to 1.09608e+07 Ns = 198.341 Pa-s, based on input of -0.8
WRN ../../source/Line.cpp:498 initialize(): Wrong catenary initial profile for Line, intializing as linear 3
Initialized Line 3
Finalizing ICs using dynamic relaxation (5X normal drag)
Fairlead tensions converged
Remaining error after 12 s = 2.73859e-05% on line 2
No Waves or Currents, or set externally
```

lines.out
```
Time	 FairTen1	 FairTen2	 FairTen3	 AnchTen1	 AnchTen2	 AnchTen3	 
(s)	 (N)       	 (N)       	 (N)       	 (N)       	 (N)       	 (N)       	 
0	 39938.5	 62832.9	 62832.9	 39935	 62829.3	 62829.3	 
0.0125	 39946.5	 60525.7	 62832.9	 39947.3	 58178.5	 62829.3	 
```

**Comment by RyanDavies19** [comment]
@hachikoi1 I just realized what is probably causing your issues. Currently WECSim and MoorDyn are only set up to run with one 6dof coupled body (this is how MoorDyn v1 was set up with WECSim, so in the interest of simplicity we left it that way for MDv2). One issue you are seeing is that WECSim is giving MoorDyn the 6 translational and rotational positions of your platform, while MoorDyn is requesting three sets of translational positions for each coupled point. This is why the positions printed in the log that the points initialize at are strange.

To fix this you need to add a 0 mass and zero volume coupled body to the input file and change the point types to Body1:


`----------------------------------------------------------- MoorDyn INPUT FILE
1:70 scale model of the IEA 15MW reference wind turbine (IEA-15-240-RWT) and UMaine VolturnUS-S semi-submersible platform https://www.ccp-wsi.ac.uk/data_repository/test_cases/test_case_015
----------------------------------------------------------- LINE TYPES
TypeName       Diam           MassDen        EA             BA/-zeta       EI             Cd             Ca             CdAx           CaAx
(name)         (m)            (kg/m)         (N)            (N-s/-)        (N-m^2)        (-)            (-)            (-)            (-) 
Chain          0.0048         0.144          2.10E+06      -1.000          0.000          2.000          0.820          0.400          0.270
----------------------- BODIES ------------------------------------------------------
ID   Attachment    X0     Y0     Z0     r0        p0        y0       Mass      CG*     I*              Volume   CdA*    Ca*
(#)     (-)               (m)    (m)    (m)   (deg)   (deg)   (deg)   (kg)        (m)     (kg-m^2)  (m^3)    (m^2)   (-)
1     Coupled        0.0     0.0    0.0    0.0       0.0       0.0       0.0          0.0     0.0             0.0        0.0      0.0
----------------------------------------------------------- POINTS                                           
ID             Attachment     X              Y              Z              M              V              CdA            CA
(#)            (word/ID)      (m)            (m)            (m)            (kg)           (m^3)          (m^2)          (-)
1              Fixed         -9.52500        0.00000       -2.86000        0.000          0.000          0.000          0.000
2              Fixed          4.41200       -7.65500       -2.86000        0.000          0.000          0.000          0.000
3              Fixed          4.41200        7.65500       -2.86000        0.000          0.000          0.000          0.000
4              Body1        -0.83443        0.00000       -0.17798        0.000          0.000          0.000          0.000
5              Body1         0.42437       -0.72680       -0.17798        0.000          0.000          0.000          0.000
6              Body1         0.42437        0.72680       -0.17798        0.000          0.000          0.000          0.000
----------------------------------------------------------- LINES                                         
ID             LineType       AttachA        AttachB        UnstrLen       NumSegs        LineOutputs
(#)            (name)         (ID)           (ID)           (m)            (-)            (-)
1              Chain          1              4              9.685          20             tp
2              Chain          2              5              9.017          20             tp
3              Chain          3              6              9.017          20             tp
----------------------------------------------------------- SOLVER OPTIONS
0.00005                                                     dtM             - time step to use in mooring integration (s)
RK2                                                         tScheme         - time integrator
2.86                                                        WtrDpth         - water depth
9.80665                                                     g               - gravity acceleration (m/s^2)
998.2072                                                    rho             - water density (kg/m^3)
1.0                                                         dtIC      		- time interval for analyzing convergence during IC gen (s)
200.0                                                       TmaxIC    		- max time for ic gen (s)
0.001                                                       threshIC  		- threshold for IC convergence (-)   
5.0                                                         CdScaleIC 		- factor by which to scale drag coefficients during dynamic relaxation (-)
0                                                           WaveKin         - wave kinematics flag (0=neglect, the only option currently supported)
3.0E+06                                                     kbot            - bottom stiffness (Pa/m)
3.0E+05                                                     cbot      		- bottom damping (Pa-s/m)
2                                                           writeLog        - write a log file
1                                                           WriteUnits      - write the units header on the output files
----------------------------------------------------------- OUTPUTS                                  
FairTen1                                           
FairTen2                                            
FairTen3                                          
AnchTen1                                            
AnchTen2                                          
AnchTen3
-----------------------------------------------------------                          
`

Sorry we didn't catch this earlier. @jtgrasb copying you here so you are aware.

**Comment by RyanDavies19** [comment]
@hachikoi1 If you are still seeing issues, it is likely that the points are not in the right location. Your points should be defined in the body's reference frame which is centered at the bodies location. At every time step including initialization, the body location is going to be defined by the mooring info in WECSim:

```
mooring(1).initial.displacement =  body(1).initial.displacement;
mooring(1).initial.axis         =  body(1).initial.axis;
mooring(1).initial.angle        =  body(1).initial.angle;
```

I would suggest using output flags like POINT#PX and BODY#PZ along with TmaxIC = 0 to check your positions at the first time step in MoorDyn to make sure they are what you mean to define.

**Comment by hachikoi1** [comment]
@RyanDavies19 
With the same parameters, WEC-Sim v5.0.1 - MoorDyn v1 work well, but WEC-Sim v6 - MoorDyn v2 reports error. I'll double-check the formatting of the input file, as I've found that moorDyn is reporting errors due to some unknown formatting issues.

I output the POINT position, and the positions of the three fairleads are zero, regardless of the definition of ```mooring(1).initial.displacement .axis .angle```

```
Time	 FairTen1	 FairTen2	 FairTen3	 AnchTen1	 AnchTen2	 AnchTen3	 POINT1PX	 POINT1PY	 POINT1PZ	 POINT2PX	 POINT2PY	 POINT2PZ	 POINT3PX	 POINT3PY	 POINT3PZ	 POINT4PX	 POINT4PY	 POINT4PZ	 POINT5PX	 POINT5PY	 POINT5PZ	 POINT6PX	 POINT6PY	 POINT6PZ	 
(s)	 (N)       	 (N)       	 (N)       	 (N)       	 (N)       	 (N)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 (m)       	 
0	 0	 0	 0	 0	 0	 0	 -9.525	 0	 -2.86	 4.412	 -7.655	 -2.86	 4.412	 7.655	 -2.86	 0	 0	 0	 0	 0	 0	 0	 -1.75245e-231	 0	 
0.0125	 56403.4	 62830.8	 62833.5	 56399.3	 62823.9	 62828.7	 -9.525	 0	 -2.86	 4.412	 -7.655	 -2.86	 4.412	 7.655	 -2.86	 -5.9351e-07	 0	 2.55729e-05	 0	 -1.91873e-05	 0	 0	 -1.62366e-233	 1.22247e-311
``` 

I'm beginning to be confused about the effect of ```mooring(1).initial.displacement .axis .angle```. Do you mean they are set respect to  platform's local coordinate system? Take the heave decay test as an example, if the initial displacement of the platform is -5m, mooring(1).initial.displacement should be 0 as mooring lines have no relative displacement with respect to the platform?

**Comment by hachikoi1** [comment]
> @hachikoi1 I just realized what is probably causing your issues. Currently WECSim and MoorDyn are only set up to run with one 6dof coupled body (this is how MoorDyn v1 was set up with WECSim, so in the interest of simplicity we left it that way for MDv2). One issue you are seeing is that WECSim is giving MoorDyn the 6 translational and rotational positions of your platform, while MoorDyn is requesting three sets of translational positions for each coupled point. This is why the positions that the points initialize at (printed in the log) are strange.
> 
> To fix this you need to add a 0 mass and zero volume coupled body to the input file and change the point types to Body1:
> 
> ```
> ----------------------------------------------------------- MoorDyn INPUT FILE
> 1:70 scale model of the IEA 15MW reference wind turbine (IEA-15-240-RWT) and UMaine VolturnUS-S semi-submersible platform https://www.ccp-wsi.ac.uk/data_repository/test_cases/test_case_015
> ----------------------------------------------------------- LINE TYPES
> TypeName       Diam           MassDen        EA             BA/-zeta       EI             Cd             Ca             CdAx           CaAx
> (name)         (m)            (kg/m)         (N)            (N-s/-)        (N-m^2)        (-)            (-)            (-)            (-) 
> Chain          0.0048         0.144          2.10E+06      -1.000          0.000          2.000          0.820          0.400          0.270
> ----------------------- BODIES ------------------------------------------------------
> ID   Attachment    X0     Y0     Z0     r0        p0        y0       Mass      CG*     I*              Volume   CdA*    Ca*
> (#)     (-)               (m)    (m)    (m)   (deg)   (deg)   (deg)   (kg)        (m)     (kg-m^2)  (m^3)    (m^2)   (-)
> 1     Coupled        0.0     0.0    0.0    0.0       0.0       0.0       0.0          0.0     0.0             0.0        0.0      0.0
> ----------------------------------------------------------- POINTS                                           
> ID             Attachment     X              Y              Z              M              V              CdA            CA
> (#)            (word/ID)      (m)            (m)            (m)            (kg)           (m^3)          (m^2)          (-)
> 1              Fixed         -9.52500        0.00000       -2.86000        0.000          0.000          0.000          0.000
> 2              Fixed          4.41200       -7.65500       -2.86000        0.000          0.000          0.000          0.000
> 3              Fixed          4.41200        7.65500       -2.86000        0.000          0.000          0.000          0.000
> 4              Body1        -0.83443        0.00000       -0.17798        0.000          0.000          0.000          0.000
> 5              Body1         0.42437       -0.72680       -0.17798        0.000          0.000          0.000          0.000
> 6              Body1         0.42437        0.72680       -0.17798        0.000          0.000          0.000          0.000
> ----------------------------------------------------------- LINES                                         
> ID             LineType       AttachA        AttachB        UnstrLen       NumSegs        LineOutputs
> (#)            (name)         (ID)           (ID)           (m)            (-)            (-)
> 1              Chain          1              4              9.685          20             tp
> 2              Chain          2              5              9.017          20             tp
> 3              Chain          3              6              9.017          20             tp
> ----------------------------------------------------------- SOLVER OPTIONS
> 0.00005                                                     dtM             - time step to use in mooring integration (s)
> RK2                                                         tScheme         - time integrator
> 2.86                                                        WtrDpth         - water depth
> 9.80665                                                     g               - gravity acceleration (m/s^2)
> 998.2072                                                    rho             - water density (kg/m^3)
> 1.0                                                         dtIC      		- time interval for analyzing convergence during IC gen (s)
> 200.0                                                       TmaxIC    		- max time for ic gen (s)
> 0.001                                                       threshIC  		- threshold for IC convergence (-)   
> 5.0                                                         CdScaleIC 		- factor by which to scale drag coefficients during dynamic relaxation (-)
> 0                                                           WaveKin         - wave kinematics flag (0=neglect, the only option currently supported)
> 3.0E+06                                                     kbot            - bottom stiffness (Pa/m)
> 3.0E+05                                                     cbot      		- bottom damping (Pa-s/m)
> 2                                                           writeLog        - write a log file
> 1                                                           WriteUnits      - write the units header on the output files
> ----------------------------------------------------------- OUTPUTS                                  
> FairTen1                                           
> FairTen2                                            
> FairTen3                                          
> AnchTen1                                            
> AnchTen2                                          
> AnchTen3
> -----------------------------------------------------------     
> ```
> 
> Sorry we didn't catch this earlier. @jtgrasb copying you here so you are aware.

I just saw the comment. I will try it. Many thanks

**Comment by hachikoi1** [comment]
Hi @RyanDavies19
Your fix worked. 
I noticed some other subtle problems: According to the definition of POINTS ATTACHMENT (https://moordyn.readthedocs.io/en/master/inputs.html#points-list), X, Y, Z are coordinates of the point relative to platform/body reference frame if “vessel” or “body#”. 
For a simulation with no initial displacement, in the moorDyn outputs, `POINT1PZ, POINT2PZ, POINT3PZ = -2.86` are in the global coordinate system, but `POINT4PZ, POINT5PZ, POINT6PZ = -0.17798` are still in the body local coordinate system (they should be `0.08571-20/70 = -0.200004285714286` in the global coordinate system). `moorDyn.Line1.Node20pz, moorDyn.Line2.Node20pz and moorDyn.Line3.Node20pz` are also `-0.17798`. Does moorDyn output result in a mixture of local and global coordinate systems? 

Similarly, I simulate a free decay test in the heave direction, with platform initial translational displacement 
```
body(1).initial.axis            =  [0 1 0];
body(1).initial.angle           =  deg2rad(0);
body(1).initial.displacement    =  [0 0 -1];
```
And correspondingly, mooring initial displacements are the same as body initial displacements
```
mooring(1).initial.displacement =  body(1).initial.displacement;
mooring(1).initial.axis         =  body(1).initial.axis;
mooring(1).initial.angle        =  body(1).initial.angle;
```
At this time, `POINT4PZ, POINT5PZ, POINT6PZ, moorDyn.Line1.Node20pz, moorDyn.Line2.Node20pz and moorDyn.Line3.Node20pz = -1.17798`. Assuming that POINT4PZ, POINT5PZ, POINT6PZ are in the local coordinate system, they should have nothing to do with the initial displacements. 

**Does the location of Body1 needs to be defined under the global coordinate system?**

**Comment by sanguinariojoe** [comment]
Everything is defined in global coordinates except those connections
attached to a body, that are defined in body local coordinates

**Comment by hachikoi1** [comment]
Hi @sanguinariojoe 
You mean that results are output in the global coordinates, except for the fairlead results? But why I give an initial displacements to the body, and fairleads are also assigned the displacements (I think they should be constant)? Or the fairlead positions are used for motion and load transformations?

**Comment by hachikoi1** [comment]
But the fairlead positions attached on the body are output in the local coordinates. I am therefore confused about it.

**Comment by sanguinariojoe** [comment]
If you applied the changes Ryan suggested to you, your body center on the
input file is defined at x,y,z=0,0,0 (null angles also). Then you are
considering different coords in your matlab code, so you start getting
inconsistencies.

Does that make any sense?

**Comment by hfchen20** [comment]
@hachikoi1 If you define body initial z_cog = -0.022, the fairlead position will be -0.022 + -0.17798 = -0.19998. This has been confirmed by running moordyn standalone.

In WEC-Sim, by defining `mooring(1).initial` conditions, you may overwrite the body cog. I don't know how wec-sim handles this, more so for decay simulations. I guess this is a question not much on moordyn itself but on the interface with wec-sim.

[lines_v2_body.txt](https://github.com/FloatingArrayDesign/MoorDyn/files/13618951/lines_v2_body.txt)

```
import moordyn

system = moordyn.Create('lines_v2_body.txt')
ndof = moordyn.NCoupledDOF(system)
nlines = moordyn.GetNumberLines(system)
print("ndof, nlines: ", ndof, nlines)

x = [0]*ndof
v = [0]*ndof
x[0:3] = [-0.00477,        0.0,       -0.022 ]
moordyn.Init(system, x, v)
```

**Comment by hachikoi1** [comment]
Hi @sanguinariojoe, @hfchen20 
You are right. In WEC-Sim input file, `mooring(1).location` should be the body COG location in the global coordinate system. And it should not be [0 0 0]. Another thing, I found BODIES location in lines.txt is not necessary to be correct ([0 0 0 0 0 0] is ok). It would be overwriten by mooring(1).location (body coordinate origin) + mooring(1).initial.displacement (body initial displacements) + body initial displacements caused by rotations.

Many thanks for your help.

Sincerely
