### ISSUE TITLE
Nonlinear Stiffness of a line

### ISSUE THREAD

**Issue by waiyanthetpaing** [FloatingArrayDesign/MoorDyn#183]
Hi,

I am coupling with MoorDynV2 and openfoam using foamMooring.  However, I cannot define nonlinear stiffness of a line.  Could you please provide a format and required fields?

[stiffness.txt](https://github.com/FloatingArrayDesign/MoorDyn/files/13934285/stiffness.txt)
![Capture](https://github.com/FloatingArrayDesign/MoorDyn/assets/156630788/d6b6eef0-8e4b-40d4-a5e8-bbab1ad0aba0)

**Comment by RyanDavies19** [comment]
Hi @waiyanthetpaing. Are you using the dev or the main branch of MoorDyn? This looks like a bug that has been recently resolved on the dev branch but was not included in the most recent releas.

**Comment by waiyanthetpaing** [comment]
Hi @RyanDavies19 , thank you for the reply.  I am just using MoorDyn to couple with OpenFOAM from this link https://gitlab.com/hfchen20/foamMooring.  I am afraid that I have no idea what version it is using.

**Comment by sanguinariojoe** [comment]
master then.

You can either change the branch yourself or wait until the next release

To change the branch just edit the .gitsubmodules file on foamMooring root
folder

**Comment by hfchen20** [comment]
Switching to dev branch resolved this issue, as reported by the user at [foamMooring](https://gitlab.com/hfchen20/foamMooring/-/issues/5#note_1729890106).

**Comment by RyanDavies19** [comment]
Good to hear. Closing this issue.

**Comment by sanguinariojoe** [comment]
P.S. I definitely shall ask Hai Fei to subscribe me to foamMooring issues
