### ISSUE TITLE
Unnecessary point in input file for lines using only rods

### ISSUE THREAD

**Issue by anjaschnepf** [FloatingArrayDesign/MoorDyn#196]
I have a MoorDyn input-file defining a cable with bending stiffness: [exampleinput.txt](https://github.com/FloatingArrayDesign/MoorDyn/files/14508108/exampleinput.txt)
To define the cable, I only use rods as connections. It would not need any points. If I delete the points-section from the input-file, I obtain the following error, and MoorDyn does not run:

`ERR source\MoorDyn2.cpp:952 moordyn::MoorDyn::ReadInFile(): Reading lines without defined points`
`Error (-3) during the Mooring System creation:`
`Exception while reading the input file`

Therefore, I defined a point in the input-file which is actually not needed in the simulation.
I am using MoorDyn v2.0.0, 2023-09-18 and v2.2.2 on Windows 10.

**Comment by RyanDavies19** [comment]
Hi @anjaschnepf thanks for the note. Unfortunately as of now MoorDyn requires both a line and a point object in every input file to run. The solution you have come up with is the correct workaround for this. Objects in MoorDyn don't interact with each other unless they are specifically defined as attached to each other , so having a dummy point and/or a dummy line is no problem with regards to the end result of your simulation.
