### ISSUE TITLE
Is there a minimum mass limit for the MassDenInAir?

### ISSUE THREAD

**Issue by TGiles1998** [FloatingArrayDesign/MoorDyn#23]
Hi,

I've been using some very light chains and the simulation seems to not accept masses less than 1kg/m? Is this a hard limit or can it be altered?

many thanks,

Thomas

**Comment by mattEhall** [comment]
Hi Thomas, 
I don't think there should be a strict minimum mass limit. My general understanding is that the main limit is the one between node natural frequencies and time step size, as discussed here https://moordyn.readthedocs.io/en/latest/usage.html#model-stability-and-segment-damping. In other words, using a smaller dtM and/or fewer segments per line should allow lighter and lighter lines. However, there could be other limiting factors that I'm not aware of.

**Comment by sanguinariojoe** [comment]
Can we close this?
