### ISSUE TITLE
Some typos, warnings and unused variables

### ISSUE THREAD

**Issue by izabala123** [FloatingArrayDesign/MoorDyn#241]
Dear all

Here I enclose you the files with some typos and warnings fixed, and unused variables commented out.
I am sorry to include them this way.

[MoorDyn_v2.zip](https://github.com/user-attachments/files/16532717/MoorDyn_v2.zip)

Best regards
Iñaki

**Comment by RyanDavies19** [comment]
@izabala123 thanks!

**Comment by izabala123** [comment]
:blush:
