### ISSUE TITLE
Tension when using Connect with Moredine in OpenFAST

### ISSUE THREAD

**Issue by yk202208** [FloatingArrayDesign/MoorDyn#32]
Why is the line tension other than the connecting part of the floating body smaller by several orders of magnitude when using Connect in OpenFAST?

I've seen this issue at least with OpenFAST2.4 and OpenFAST3.0.
For example, when connecting with anchor-chain①-rope-chain②-vessel, the tension of chain① and rope becomes extremely low compared to the tension of chain②. I think the chain② tension is at a reasonable level, but I would like to know the correct rope and chain① tension as well.

I can't share all the information because it is related to the confidentiality of the project, but if you connect like the example, FairTen 7-9 will output a reasonable tension, but FairTen 1-6 will output a value that is several orders of magnitude smaller.

**Comment by yk202208** [comment]
Sorry, I forgot to attach the sample.

[sample_MoorDyn.txt](https://github.com/mattEhall/MoorDyn/files/9255811/sample_MoorDyn.txt)

**Comment by mattEhall** [comment]
See 432349
This will be changed in the future to match the behavior you're expecting.

**Comment by yk202208** [comment]
Thank you.

**Comment by sanguinariojoe** [comment]
Is this fixed then? Can we close this?
