### ISSUE TITLE
how to output the Node position by matlab 

### ISSUE THREAD

**Issue by yuanxiuwen0520** [FloatingArrayDesign/MoorDyn#39]
I want to use the next codes to obtain the Node position, but it was maybe unsuccessful.
calllib('MoorDyn','GetNodePos',2, 2, XX); 
 when XX is number ,it will be display ans=-1,so that I can not obtain the calculation node position data , I want to know the data type of the XX, and the correct import example.

**Comment by sanguinariojoe** [comment]
Have you tried [MoorDyn v2](https://github.com/mattEhall/MoorDyn/tree/v2)? You have the documentation [here](https://moordyn-v2.readthedocs.io/en/latest/) and even [a matlab test](https://github.com/mattEhall/MoorDyn/blob/v2/tests/matlab_bindings.m.in)
