### ISSUE TITLE
Possible bug in Misc.cpp

### ISSUE THREAD

**Issue by nhu-vnguyen** [FloatingArrayDesign/MoorDyn#48]
On lines 293 and 298

https://github.com/mattEhall/MoorDyn/blob/09284c25a03a45dc183234be8e26edd6f695ca85/source/Misc.cpp#L291-L303

l=v.norm() is the vector magnitude/hypotenuse so should 'phi' be from asin or acos instead of atan?

**Comment by sanguinariojoe** [comment]
Nice catch! It should be

`v(Eigen::seqN(0, 2)).norm();`

I am fixing it ASAP

**Comment by sanguinariojoe** [comment]
Here we go: https://github.com/mattEhall/MoorDyn/pull/50
