### ISSUE TITLE
moordyn gives for the same platform position different values of net forces

### ISSUE THREAD

**Issue by relhamoud** [FloatingArrayDesign/MoorDyn#56]
Hi,

I couple MoorDyn with MATLAB. In order to test MoorDyn v1.01.02C, i made a for loop and by mistake i put time equals 0 and the position and velocity vectors are constant and do not change.
I was surprised that MoorDyn gives for each increment a new vector of net forces !!!

Please could anyone explain to me  why i obtain this ?

Best Regards

**Comment by mattEhall** [comment]
Hi, MoorDyn is a dynamic model so if the platform/fairleads are not moving but the mooring system itself is not already at static equilibrium, it will move until it settles into static equilibrium.
