### ISSUE TITLE
External Wave Kinematics is only for line nodes

### ISSUE THREAD

**Issue by AlexWKinley** [FloatingArrayDesign/MoorDyn#67]
Using the WaveKin = 1 option allows users to get the position of nodes and then they can set the water current and acceleration at those points. The current implementation of this only does line nodes. Connections, rods, and bodies are not able to have their water kinematics set using this method. Assuming that handling other structures is desired functionality, should it be implemented by keeping the current interface or would it be preferable to expand the interface in some way to allow discriminating between the different objects?

Keeping the current interface so that MoorDyn_ExternalWaveKinGetCoordinates returns the coordinates of line nodes, rod nodes, connections, bodies would mean that if you want to handle all those other structures in the same way, then your code wouldn't have to change at all. But if someone wanted to do different calculations for bodies than or lines or something, then the current interface wouldn't allow that.

**Comment by mattEhall** [comment]
Hi Alex,
Good question. Personally I'd be in favor of using the same approach for Points, Rods, and Bodies--for simplicity. Currently the formulation for those calculations (some of it might be implemented, the rest might just be in my head) would work fine with that approach. If there was a more advanced formulation, we might want to deal with additional things (for example, getting wave kinematics at multiple points around a body, or getting the free surface slope) but I think that's TBD and maybe not worth the trouble.

It would be good to hear what others like @djanders19 think about it...

**Comment by AlexWKinley** [comment]
In #71 this has been changed so that external wave kinematics does all nodes including points, rods, and bodies.
