### ISSUE TITLE
How do output channels get written in the refactored code?

### ISSUE THREAD

**Issue by mattEhall** [FloatingArrayDesign/MoorDyn#68]
Could someone help me understand how writing output channels to the output file works in the latest v2 branch code? There used to be a getOutput function (https://github.com/FloatingArrayDesign/MoorDyn/blob/b31c7c4f7bc2d0e61c29bfffd361920c796aa51e/source/MoorDyn.cpp#L306) that would call methods like Line::Output to write the output files.

It looks like Line::Output has been renamed Line::GetLineOutput, but I can't find anything that calls it anymore. Am I missing something? How does output file writing work in the latest version of the code?

**Comment by sanguinariojoe** [comment]
When an output is required (both on `moordyn::MoorDyn::Init()` & `moordyn::MoorDyn::Step()`) https://github.com/FloatingArrayDesign/MoorDyn/blob/v2/source/MoorDyn2.cpp#L1953 is called, which is redirecting the job to https://github.com/FloatingArrayDesign/MoorDyn/blob/v2/source/MoorDyn2.hpp#L713

There `moordyn::Line::GetLineOutput()`, `moordyn::Connection::GetConnectionOutput()` and `moordyn::Rod::GetRodOutput()` are called
