### ISSUE TITLE
Clang++ compile issue with Waves

### ISSUE THREAD

**Issue by RyanDavies19** [FloatingArrayDesign/MoorDyn#72]
I was getting my branch up to date today (from before the waves object was created) and merged all the recent updates in. I have been compiling the library from the makefile in compile/DYLIB/makefile. v2 no longer compiles, and clang throws an error: linker command failed with exit code 1. It says this is caused by undefined symbols for architecture x86_64, all of which are related to the waves object. @sanguinariojoe, any ideas?

<img width="1440" alt="Screenshot 2023-05-25 at 1 54 13 PM" src="https://github.com/FloatingArrayDesign/MoorDyn/assets/101124339/d2fdebdf-9d48-425a-99f2-122cfd3f12bd">

**Comment by sanguinariojoe** [comment]
Damn! Makefiles! I hate you!

Now it should compile properly. Let me know please

**Comment by RyanDavies19** [comment]
That fixed it, thank you!
