### ISSUE TITLE
On Control of Endpoints of Truncated Mooring Lines

### ISSUE THREAD

**Issue by ldd289806329** [FloatingArrayDesign/MoorDyn#79]
Hello, I would like to use Moordyn for my project and may need to make some changes to its source code. It is a real-time hybrid test of the mooring system, which requires Moordyn to be made into a numerical substructure and an experimental substructure. The mooring line needs to be cut off from the middle, with a portion of the upper mooring line retained, and specific displacement or force applied at the cutoff point to simulate the true dynamic response of the mooring line in an unbroken mooring. The problem I am facing now is that I don't know how to apply displacement or force in real-time at the cutoff point, or how to control the endpoint of the mooring line in real-time through external programs such as MATLAB. I hope you can give me some suggestions or tell me where to modify the source code? The following is a schematic diagram of my project.thanks
image

**Comment by ldd289806329** [comment]
![image](https://github.com/FloatingArrayDesign/MoorDyn/assets/111641893/d87fa5d9-4e06-4359-80c9-82cb1b70ad32)

**Comment by sanguinariojoe** [comment]
I do not think you need to modify the MoorDyn source code even a bit. MoorDyn v2 gives you all the functionality you need. It depends of course on what do you want specifically. I think you want to set up each line with the fairlead modelled as a coupled connection and the point A modelled as a coupled cantilevered rod, so you can provide the position of the point A as well as the tangent.

You can use MoorDyn v2 in MATLAB if you want ([you even has a test](https://github.com/FloatingArrayDesign/MoorDyn/blob/v2/tests/matlab_bindings.m.in)). Otherwise you can connect with MoorDyn by a Python wrapper (https://se.mathworks.com/help/matlab/call-python-libraries.html) or use the TCP utilities to have them running separately and communicating by the network.

**Comment by ldd289806329** [comment]
If the source program is not modified, the definition of rot in the input file does not have an interface for real-time update of displacement. The following figure shows the input file for ROT
![1687255294453](https://github.com/FloatingArrayDesign/MoorDyn/assets/111641893/c9f26808-2a5d-4801-a73e-2833c4638c96)
![1687255294457](https://github.com/FloatingArrayDesign/MoorDyn/assets/111641893/829bb8ae-acaf-4523-9d9b-d39f5f1db044)
And if Rots is used as the coupling point connected to Point A, defined as a "Pinned" Rods, the length of the Rods will not change, one end point is fixed, and the range of motion of the other end point will be limited?
In addition, it is mentioned in the V2 version help file that there is a defined "Coupled" point that can be controlled by external programs, but there is also a similar issue where there is no controlled interface in the input file. May I ask if you have any suggestions? The following figure is an explanation of the 'Coupled' point
![1687255294463](https://github.com/FloatingArrayDesign/MoorDyn/assets/111641893/ac3c82d7-c85f-45ab-b896-1c6ec98e1399)

**Comment by sanguinariojoe** [comment]
[Rods can be of type coupled as well](https://github.com/FloatingArrayDesign/MoorDyn/blob/v2/source/MoorDyn2.cpp#L1690). The documentation seems incomplete (Would you open a new issue about that please).

**Comment by ldd289806329** [comment]
![image](https://github.com/FloatingArrayDesign/MoorDyn/assets/111641893/b84c4b45-5452-463c-9f5c-fd1edd0ea7db)

isn't this the latest version? Could you provide me with a download address for the latest version of the instructions

**Comment by ldd289806329** [comment]
Based on your suggestion, if I don't make any changes to the source code, I have reviewed your Moordyn2.cpp and Rod.cpp, but I still don't know how to modify the input file to adapt to my project. How to control the movement of "Coupled" points in external programs? Do you have any similar cases to share here?
![1687332788658](https://github.com/FloatingArrayDesign/MoorDyn/assets/111641893/11d7a30b-4f12-44b6-b0ed-3ca1fc2b605d)
![1687332788663](https://github.com/FloatingArrayDesign/MoorDyn/assets/111641893/b16bf1a7-5ada-489a-afff-361a33ac9931)
![image](https://github.com/FloatingArrayDesign/MoorDyn/assets/111641893/aa30e7ac-e9c6-46de-b084-23c1e536d5ab)
There is no interface with the calling program/script in the input file

**Comment by ldd289806329** [comment]
Can you give me some advice? Thank you.

**Comment by sanguinariojoe** [comment]
Look the new docs here:

https://moordyn-v2.readthedocs.io/en/latest/structure.html
https://moordyn-v2.readthedocs.io/en/latest/coupling.html

You just need to change the attachment on RODS section to **coupled**. The same holds for POINTS section, i.e. change the Type to **coupled** (if the top structure is moving)
