### ISSUE TITLE
The documentation seems incomplete.

### ISSUE THREAD

**Issue by ldd289806329** [FloatingArrayDesign/MoorDyn#80]
Rods can be of type coupled as well，but I don't know how to implement it. Can you give me some help documents? thanks
In addition, it is mentioned in the V2 version help file that there is a defined "Coupled" point that can be controlled by external programs, but there is also a similar issue where there is no controlled interface in the input file.
![image](https://github.com/FloatingArrayDesign/MoorDyn/assets/111641893/9ae2876f-5a33-4e6b-8e05-d91a697d595e)

**Comment by sanguinariojoe** [comment]
I have made some changes on the documentation:

https://moordyn-v2.readthedocs.io/en/latest/structure.html
https://moordyn-v2.readthedocs.io/en/latest/coupling.html
